name: Create PR for YAML Files

on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  fetch-intellij-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch IntelliJ IDEA Release
        id: fetch-release
        run: |
          release_data=$(curl -s https://api.github.com/repos/JetBrains/intellij-community/releases/latest)
          release_version=$(echo $release_data | jq -r '.name' | awk '{print $3}')
          echo "::set-output name=version::$release_version"
          echo "RELEASE_YEAR_VERSION=$release_version" >> $GITHUB_ENV

  update-ion-intellij-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Find and stage YAML files
        run: | 
          cd $GITHUB_WORKSPACE/.github/workflows
      
          for file in *.yml; do
            echo "Modified $file"
          sed -i '/matrix:/,/]/s/]$/, "'"$RELEASE_YEAR_VERSION"'"]/g' $file
          done
      - name: Create pull request for the new changes
        uses: peter-evans/create-pull-request@v6
        with:
          git-token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update ion-intellij-plugin to be compatible with the new IntelliJ'
          branch: update-plugin
